import { YouTuber, DayHeatmap } from '../types';

const generateHeatmap = (peakDay: string, peakSlotIndex: number): DayHeatmap[] => {
  const days = [
    { day: 'Man', fullDay: 'Mandag' },
    { day: 'Tir', fullDay: 'Tirsdag' },
    { day: 'Ons', fullDay: 'Onsdag' },
    { day: 'Tor', fullDay: 'Torsdag' },
    { day: 'Fre', fullDay: 'Fredag' },
    { day: 'Lør', fullDay: 'Lørdag' },
    { day: 'Søn', fullDay: 'Søndag' },
  ];
  const timeSlots = ['00-04', '04-08', '08-12', '12-16', '16-20', '20-24'];
  return days.map((d) => {
    const isPeakDay = d.fullDay === peakDay;
    const slots = timeSlots.map((time, idx) => {
      let base = 25 + Math.floor(Math.sin((idx + 1) / 2) * 20);
      if (idx === 4) base += 35; // 16-20 is always stronger
      if (idx === 3) base += 20; // 12-16
      if (idx === 0) base = 8;
      if (idx === 1) base = 12;

      if (isPeakDay) {
        base += 20;
        if (idx === peakSlotIndex) base = 96 + Math.floor(Math.random() * 4);
      }
      return {
        time,
        score: Math.min(100, Math.max(10, base)),
      };
    });
    return {
      day: d.day,
      fullDay: d.fullDay,
      slots,
    };
  });
};

export const DANISH_YOUTUBERS: YouTuber[] = [
  {
    id: 'alexander-husum',
    name: 'Alexander Husum',
    channelName: 'Alexander Husum',
    handle: '@AlexanderHusum',
    avatarUrl:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Underholdning',
    subscribers: 468000,
    totalViews: 382450000,
    monthlyViews: 8950000,
    monthlyGrowthPct: 14.2,
    monthlySubGain: 5200,
    videoCount: 940,
    avgViewsPerVideo: 406800,
    engagementRate: 5.6,
    rankPosition: 1,
    bestPostingTime: {
      day: 'Søndag',
      hours: '15:00 - 17:30',
      score: 98,
      boostPercent: 34,
      recommendation:
        'Søndag eftermiddag giver 34% flere visninger de første 4 timer grundet familietid og lektiefri for unge seere.',
    },
    weeklyHeatmap: generateHeatmap('Søndag', 4),
    recentVideos: [
      {
        id: 'ah-1',
        title: 'Sidst der forlader boksen vinder 50.000 kr!',
        views: 342000,
        uploadDate: 'For 2 dage siden',
        likes: 18500,
        duration: '22:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@AlexanderHusum/videos',
      },
      {
        id: 'ah-2',
        title: 'Vi overnattede i en forladt vandpark!',
        views: 520000,
        uploadDate: 'For 6 dage siden',
        likes: 27900,
        duration: '28:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@AlexanderHusum/videos',
      },
      {
        id: 'ah-3',
        title: 'Hvem kender mig bedst? (Kæreste vs. Bedste Ven)',
        views: 288000,
        uploadDate: 'For 1 uge siden',
        likes: 14200,
        duration: '18:02',
        thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@AlexanderHusum/videos',
      },
      {
        id: 'ah-4',
        title: '24 Timer på en Øde Ø uden mad!',
        views: 465000,
        uploadDate: 'For 2 uger siden',
        likes: 24100,
        duration: '25:30',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@AlexanderHusum/videos',
      },
      {
        id: 'ah-5',
        title: 'Bygger Danmarks største hemmelige rum under sengen',
        views: 610000,
        uploadDate: 'For 3 uger siden',
        likes: 36500,
        duration: '31:12',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@AlexanderHusum/videos',
      },
    ],
    bio: 'Danmarks største underholdningskanal med vilde challenges, 24-timers eksperimenter og sjove pranks med vennerne.',
    joinedYear: 2013,
    topAudienceAge: '13-24 år',
  },
  {
    id: 'morten-munster',
    name: 'Morten Münster',
    channelName: 'Morten Münster',
    handle: '@MortenMunster',
    avatarUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Comedy',
    subscribers: 452000,
    totalViews: 351200000,
    monthlyViews: 7600000,
    monthlyGrowthPct: 10.8,
    monthlySubGain: 3800,
    videoCount: 780,
    avgViewsPerVideo: 450250,
    engagementRate: 6.2,
    rankPosition: 2,
    bestPostingTime: {
      day: 'Fredag',
      hours: '16:00 - 18:30',
      score: 95,
      boostPercent: 28,
      recommendation:
        'Fredag kl. 16:30 fanger weekendstarten perfekt for skoleelever og teenagere på vej på ferie eller fri.',
    },
    weeklyHeatmap: generateHeatmap('Fredag', 4),
    recentVideos: [
      {
        id: 'mm-1',
        title: 'Når man lyver på sin datingprofil 😂',
        views: 310000,
        uploadDate: 'For 3 dage siden',
        likes: 21000,
        duration: '14:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@MortenMunster/videos',
      },
      {
        id: 'mm-2',
        title: 'Bubber og Morten spiser de stærkeste chilier i verden',
        views: 640000,
        uploadDate: 'For 8 dage siden',
        likes: 38400,
        duration: '21:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@MortenMunster/videos',
      },
      {
        id: 'mm-3',
        title: 'Forældre typer til forældremøde!',
        views: 415000,
        uploadDate: 'For 2 uger siden',
        likes: 26500,
        duration: '12:35',
        thumbnailUrl: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@MortenMunster/videos',
      },
      {
        id: 'mm-4',
        title: 'Reagerer på mine første YouTube videoer (CRINGE)',
        views: 385000,
        uploadDate: 'For 3 uger siden',
        likes: 24300,
        duration: '16:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@MortenMunster/videos',
      },
      {
        id: 'mm-5',
        title: 'Når læreren mister tålmodigheden i klassen',
        views: 490000,
        uploadDate: 'For 1 måned siden',
        likes: 31200,
        duration: '13:55',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@MortenMunster/videos',
      },
    ],
    bio: 'Danmarks comedy-konge på YouTube med sketches, sketch-serier, skøre parodier og gæsteoptrædener.',
    joinedYear: 2011,
    topAudienceAge: '14-29 år',
  },
  {
    id: 'robinsamse',
    name: 'RobinSamse (Robin & Samrita)',
    channelName: 'RobinSamse',
    handle: '@RobinSamse',
    avatarUrl:
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Gaming',
    subscribers: 268000,
    totalViews: 294800000,
    monthlyViews: 5400000,
    monthlyGrowthPct: 8.9,
    monthlySubGain: 2200,
    videoCount: 3150,
    avgViewsPerVideo: 93500,
    engagementRate: 4.8,
    rankPosition: 3,
    bestPostingTime: {
      day: 'Lørdag',
      hours: '10:00 - 13:00',
      score: 93,
      boostPercent: 24,
      recommendation:
        'Lørdag formiddag er ideel for Minecraft- og Roblox-fællesskabet med masser af morgentimer.',
    },
    weeklyHeatmap: generateHeatmap('Lørdag', 3),
    recentVideos: [
      {
        id: 'rs-1',
        title: 'Vi bygger det HEMMELIGSTE slot i Minecraft Hardcore!',
        views: 98000,
        uploadDate: 'For 1 dag siden',
        likes: 6400,
        duration: '31:20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RobinSamse/videos',
      },
      {
        id: 'rs-2',
        title: 'Samrita prøver et umuligt Roblox Obby map!',
        views: 114000,
        uploadDate: 'For 4 dage siden',
        likes: 8200,
        duration: '24:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1612287233207-628d655f269a?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RobinSamse/videos',
      },
      {
        id: 'rs-3',
        title: 'Robin og Samse bager kager i VR!',
        views: 89000,
        uploadDate: 'For 6 dage siden',
        likes: 5900,
        duration: '19:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RobinSamse/videos',
      },
      {
        id: 'rs-4',
        title: 'Minecraft men hver blok er et LYKKEHJUL!',
        views: 126000,
        uploadDate: 'For 1 uge siden',
        likes: 9100,
        duration: '27:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RobinSamse/videos',
      },
      {
        id: 'rs-5',
        title: 'Overlever 100 dage på en sky i Minecraft',
        views: 145000,
        uploadDate: 'For 2 uger siden',
        likes: 11200,
        duration: '34:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RobinSamse/videos',
      },
    ],
    bio: 'Danmarks mest elskede gaming-par. Hygge, Minecraft, Roblox og familiesjov hver evig eneste uge!',
    joinedYear: 2012,
    topAudienceAge: '8-18 år',
  },
  {
    id: 'judex',
    name: 'David Jæger (Judex)',
    channelName: 'Judex',
    handle: '@JudexDK',
    avatarUrl:
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Gaming',
    subscribers: 234000,
    totalViews: 204500000,
    monthlyViews: 4850000,
    monthlyGrowthPct: 12.5,
    monthlySubGain: 3100,
    videoCount: 1420,
    avgViewsPerVideo: 144000,
    engagementRate: 6.8,
    rankPosition: 4,
    bestPostingTime: {
      day: 'Onsdag',
      hours: '15:30 - 18:00',
      score: 92,
      boostPercent: 26,
      recommendation:
        'Onsdag eftermiddag er lille-fredag på gaming og giver stærk visningsophobning før weekenden.',
    },
    weeklyHeatmap: generateHeatmap('Onsdag', 4),
    recentVideos: [
      {
        id: 'jx-1',
        title: 'Jeg overlevede 100 DAGE i et Mutant Minecraft Univers!',
        views: 184000,
        uploadDate: 'For 2 dage siden',
        likes: 12400,
        duration: '35:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JudexDK/videos',
      },
      {
        id: 'jx-2',
        title: 'Test af Danmarks vildeste hemmelige gaming gear',
        views: 142000,
        uploadDate: 'For 5 dage siden',
        likes: 9100,
        duration: '20:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JudexDK/videos',
      },
      {
        id: 'jx-3',
        title: 'Fangede en hacker i min egen Minecraft server!',
        views: 220000,
        uploadDate: 'For 1 uge siden',
        likes: 16700,
        duration: '26:45',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JudexDK/videos',
      },
      {
        id: 'jx-4',
        title: 'Minecraft men monstrene bliver 10x STÆRKERE hver nat!',
        views: 195000,
        uploadDate: 'For 2 uger siden',
        likes: 14800,
        duration: '30:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JudexDK/videos',
      },
      {
        id: 'jx-5',
        title: 'Vi prankede hele serveren med usynlighed!',
        views: 160000,
        uploadDate: 'For 3 uger siden',
        likes: 11900,
        duration: '22:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1612287233207-628d655f269a?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JudexDK/videos',
      },
    ],
    bio: 'Actionspækket gaming, vilde Minecraft udfordringer og sjove historier fra Danmarks Minecraft-ekspert.',
    joinedYear: 2014,
    topAudienceAge: '10-20 år',
  },
  {
    id: 'jas-mika',
    name: 'Jasmin & Mika',
    channelName: 'Jas & Mika',
    handle: '@JasogMika',
    avatarUrl:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Vlogs & Livsstil',
    subscribers: 252000,
    totalViews: 191300000,
    monthlyViews: 6100000,
    monthlyGrowthPct: 15.6,
    monthlySubGain: 4400,
    videoCount: 480,
    avgViewsPerVideo: 398500,
    engagementRate: 7.1,
    rankPosition: 5,
    bestPostingTime: {
      day: 'Søndag',
      hours: '11:00 - 14:00',
      score: 96,
      boostPercent: 31,
      recommendation:
        'Søndag formiddag er højdepunktet for parrets livsstilsvlogs og hyggestunder sammen.',
    },
    weeklyHeatmap: generateHeatmap('Søndag', 3),
    recentVideos: [
      {
        id: 'jm-1',
        title: 'Vi overrasker med en kæmpe hemmelighed! 🎉',
        views: 450000,
        uploadDate: 'For 2 dage siden',
        likes: 31200,
        duration: '19:25',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JasogMika/videos',
      },
      {
        id: 'jm-2',
        title: '24 TIMER hvor Mika skal sige JA til ALT Jasmin siger!',
        views: 380000,
        uploadDate: 'For 5 dage siden',
        likes: 24800,
        duration: '23:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JasogMika/videos',
      },
      {
        id: 'jm-3',
        title: 'Vores nye drømmehus rundtur! (Room Tour)',
        views: 520000,
        uploadDate: 'For 1 uge siden',
        likes: 39000,
        duration: '27:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JasogMika/videos',
      },
      {
        id: 'jm-4',
        title: 'Hvem kan lave den bedste 3-retters menu for 100 kr?',
        views: 295000,
        uploadDate: 'For 2 uger siden',
        likes: 22100,
        duration: '21:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JasogMika/videos',
      },
      {
        id: 'jm-5',
        title: 'Vi bytter liv i 24 timer (Kaotisk)',
        views: 340000,
        uploadDate: 'For 3 uger siden',
        likes: 26400,
        duration: '24:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@JasogMika/videos',
      },
    ],
    bio: 'Danmarks mest populære par på YouTube. Vlogs, par-challenges, rejser og hverdagsdrama med et glimt i øjet.',
    joinedYear: 2018,
    topAudienceAge: '12-28 år',
  },
  {
    id: 'rasmus-brohave',
    name: 'Rasmus Brohave',
    channelName: 'Rasmus Brohave',
    handle: '@RasmusBrohave',
    avatarUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Vlogs & Livsstil',
    subscribers: 289000,
    totalViews: 146800000,
    monthlyViews: 3200000,
    monthlyGrowthPct: 6.4,
    monthlySubGain: 1800,
    videoCount: 520,
    avgViewsPerVideo: 282000,
    engagementRate: 4.5,
    rankPosition: 6,
    bestPostingTime: {
      day: 'Torsdag',
      hours: '17:00 - 19:30',
      score: 91,
      boostPercent: 22,
      recommendation:
        'Torsdag aften fanger seerne lige inden fredagen, ideelt for velproducerede reportager og samtaler.',
    },
    weeklyHeatmap: generateHeatmap('Torsdag', 4),
    recentVideos: [
      {
        id: 'rb-1',
        title: 'Hvad kan man få for 1.000 kr. i Tokyo? 🇯🇵',
        views: 215000,
        uploadDate: 'For 3 dage siden',
        likes: 12500,
        duration: '21:30',
        thumbnailUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RasmusBrohave/videos',
      },
      {
        id: 'rb-2',
        title: 'Jeg arbejdede som Falck-redder i 24 timer',
        views: 310000,
        uploadDate: 'For 1 uge siden',
        likes: 19800,
        duration: '26:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RasmusBrohave/videos',
      },
      {
        id: 'rb-3',
        title: 'Hvad tjener en pilot i Danmark? (Hvad kan man blive)',
        views: 275000,
        uploadDate: 'For 2 uger siden',
        likes: 16200,
        duration: '24:45',
        thumbnailUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RasmusBrohave/videos',
      },
      {
        id: 'rb-4',
        title: 'Tester Danmarks dyreste luksus-hotel',
        views: 190000,
        uploadDate: 'For 3 uger siden',
        likes: 11400,
        duration: '18:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RasmusBrohave/videos',
      },
      {
        id: 'rb-5',
        title: 'En dag som dyrepasser i Zoologisk Have',
        views: 230000,
        uploadDate: 'For 1 måned siden',
        likes: 14700,
        duration: '22:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RasmusBrohave/videos',
      },
    ],
    bio: 'Professionelle vlogs, dybdegående interviews, rejsefilm og "Hvad kan man blive"-serien.',
    joinedYear: 2012,
    topAudienceAge: '16-32 år',
  },
  {
    id: 'niki-topgaard',
    name: 'Niki Topgaard',
    channelName: 'Niki Topgaard',
    handle: '@NikiTopgaard',
    avatarUrl:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Underholdning',
    subscribers: 228000,
    totalViews: 172400000,
    monthlyViews: 4100000,
    monthlyGrowthPct: 9.3,
    monthlySubGain: 2400,
    videoCount: 390,
    avgViewsPerVideo: 442000,
    engagementRate: 5.9,
    rankPosition: 7,
    bestPostingTime: {
      day: 'Fredag',
      hours: '15:00 - 17:00',
      score: 94,
      boostPercent: 27,
      recommendation:
        'Fredag eftermiddag giver maksimal spredning til Nikis actionfyldte sketches og humor.',
    },
    weeklyHeatmap: generateHeatmap('Fredag', 4),
    recentVideos: [
      {
        id: 'nt-1',
        title: 'De Vildeste Special Effects på 1 time!',
        views: 295000,
        uploadDate: 'For 4 dage siden',
        likes: 21400,
        duration: '16:45',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@NikiTopgaard/videos',
      },
      {
        id: 'nt-2',
        title: 'Zombier i Netto! (Kortfilm)',
        views: 480000,
        uploadDate: 'For 1 uge siden',
        likes: 34100,
        duration: '19:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@NikiTopgaard/videos',
      },
      {
        id: 'nt-3',
        title: 'Når man ser gyserfilm alene om natten 😱',
        views: 360000,
        uploadDate: 'For 2 uger siden',
        likes: 26800,
        duration: '14:20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@NikiTopgaard/videos',
      },
      {
        id: 'nt-4',
        title: 'Bag kulisserne på vores vildeste stunt nogensinde',
        views: 245000,
        uploadDate: 'For 3 uger siden',
        likes: 18200,
        duration: '21:05',
        thumbnailUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@NikiTopgaard/videos',
      },
      {
        id: 'nt-5',
        title: 'Hvem overlever flugten fra det forheksede hus?',
        views: 410000,
        uploadDate: 'For 1 måned siden',
        likes: 29500,
        duration: '23:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@NikiTopgaard/videos',
      },
    ],
    bio: 'Kreative kortfilm, vilde stunts, VFX effekter og Danmarks mest gennemarbejdede sketches.',
    joinedYear: 2010,
    topAudienceAge: '12-25 år',
  },
  {
    id: 'comkean',
    name: 'Charly (ComKean)',
    channelName: 'ComKean',
    handle: '@ComKean',
    avatarUrl:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Gaming',
    subscribers: 198000,
    totalViews: 182300000,
    monthlyViews: 3700000,
    monthlyGrowthPct: 7.8,
    monthlySubGain: 1900,
    videoCount: 2100,
    avgViewsPerVideo: 86800,
    engagementRate: 4.4,
    rankPosition: 8,
    bestPostingTime: {
      day: 'Lørdag',
      hours: '14:00 - 16:30',
      score: 90,
      boostPercent: 21,
      recommendation:
        'Lørdag eftermiddag for hyggelig gaming med humor, Roblox og sjove indie-spil.',
    },
    weeklyHeatmap: generateHeatmap('Lørdag', 4),
    recentVideos: [
      {
        id: 'ck-1',
        title: 'Dette Roblox spil burde være FORBUDT for sjov!',
        views: 110000,
        uploadDate: 'For 1 dag siden',
        likes: 6700,
        duration: '17:20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1612287233207-628d655f269a?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@ComKean/videos',
      },
      {
        id: 'ck-2',
        title: 'ComKean smager det mærkeligste slik fra Japan',
        views: 145000,
        uploadDate: 'For 4 dage siden',
        likes: 9200,
        duration: '15:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@ComKean/videos',
      },
      {
        id: 'ck-3',
        title: 'Kan man vinde dette umulige simulator spil?',
        views: 95000,
        uploadDate: 'For 1 uge siden',
        likes: 5800,
        duration: '19:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@ComKean/videos',
      },
      {
        id: 'ck-4',
        title: 'Vi bygger det største tivoli i Roblox Park',
        views: 120000,
        uploadDate: 'For 2 uger siden',
        likes: 8100,
        duration: '22:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@ComKean/videos',
      },
      {
        id: 'ck-5',
        title: 'ComKean reagerer på de sjoveste spil-fails',
        views: 135000,
        uploadDate: 'For 3 uger siden',
        likes: 9400,
        duration: '16:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@ComKean/videos',
      },
    ],
    bio: 'Gaming med masser af grin, skæve indie-spil, Roblox og hyggelige reaktioner for hele familien.',
    joinedYear: 2013,
    topAudienceAge: '9-17 år',
  },
  {
    id: 'trier-gaming',
    name: 'Emil & Mikkel Trier',
    channelName: 'Trier Gaming',
    handle: '@TrierGaming',
    avatarUrl:
      'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Gaming',
    subscribers: 214000,
    totalViews: 158900000,
    monthlyViews: 2900000,
    monthlyGrowthPct: 5.4,
    monthlySubGain: 1200,
    videoCount: 1850,
    avgViewsPerVideo: 85900,
    engagementRate: 3.9,
    rankPosition: 9,
    bestPostingTime: {
      day: 'Tirsdag',
      hours: '16:00 - 18:00',
      score: 89,
      boostPercent: 19,
      recommendation:
        'Tirsdag efter skoletid for faste serier og Minecraft serverevents.',
    },
    weeklyHeatmap: generateHeatmap('Tirsdag', 4),
    recentVideos: [
      {
        id: 'tg-1',
        title: 'Trier Brødrene bygger den ultimative Minecraft hemmelige base',
        views: 78000,
        uploadDate: 'For 2 dage siden',
        likes: 4900,
        duration: '22:05',
        thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@TrierGaming/videos',
      },
      {
        id: 'tg-2',
        title: 'Fanger bedrageren i Minecraft Among Us med vennerne',
        views: 92000,
        uploadDate: 'For 5 dage siden',
        likes: 6200,
        duration: '18:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@TrierGaming/videos',
      },
      {
        id: 'tg-3',
        title: '100 dage på en enkelt Lucky Block ø!',
        views: 115000,
        uploadDate: 'For 1 uge siden',
        likes: 7800,
        duration: '27:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@TrierGaming/videos',
      },
      {
        id: 'tg-4',
        title: 'Mikkel vs Emil: Bygge-konkurrence på 10 minutter',
        views: 84000,
        uploadDate: 'For 2 uger siden',
        likes: 5400,
        duration: '16:30',
        thumbnailUrl: 'https://images.unsplash.com/photo-1612287233207-628d655f269a?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@TrierGaming/videos',
      },
      {
        id: 'tg-5',
        title: 'Trier Serveren åbner ny vild verden!',
        views: 69000,
        uploadDate: 'For 3 uger siden',
        likes: 4300,
        duration: '20:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@TrierGaming/videos',
      },
    ],
    bio: 'Trier brødrene leverer dansk gaming, Minecraft server-sjov og god underholdning til børn og unge.',
    joinedYear: 2011,
    topAudienceAge: '8-16 år',
  },
  {
    id: 'brian-mengel-brizze',
    name: 'Brian Mengel (Brizze)',
    channelName: 'Brizze FC',
    handle: '@BrizzeFC',
    avatarUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Sport & Fodbold',
    subscribers: 172000,
    totalViews: 92400000,
    monthlyViews: 2600000,
    monthlyGrowthPct: 8.7,
    monthlySubGain: 1700,
    videoCount: 410,
    avgViewsPerVideo: 225300,
    engagementRate: 5.3,
    rankPosition: 10,
    bestPostingTime: {
      day: 'Søndag',
      hours: '18:00 - 20:30',
      score: 93,
      boostPercent: 25,
      recommendation:
        'Søndag aften efter Superliga-runden og fodboldkampe er seerne ekstra modtagelige for fodboldskills.',
    },
    weeklyHeatmap: generateHeatmap('Søndag', 4),
    recentVideos: [
      {
        id: 'bz-1',
        title: 'Kan jeg score på en Superliga-målmand fra midterlinjen?',
        views: 210000,
        uploadDate: 'For 3 dage siden',
        likes: 14800,
        duration: '18:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@BrizzeFC/videos',
      },
      {
        id: 'bz-2',
        title: 'Drible-challenge mod Danmarks største talenter!',
        views: 175000,
        uploadDate: 'For 1 uge siden',
        likes: 11200,
        duration: '15:55',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@BrizzeFC/videos',
      },
      {
        id: 'bz-3',
        title: 'Freestyle fodbold i Københavns gader (Folk går amok!)',
        views: 195000,
        uploadDate: 'For 2 uger siden',
        likes: 13500,
        duration: '14:20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@BrizzeFC/videos',
      },
      {
        id: 'bz-4',
        title: 'Crossbar Challenge: Den der rammer først vinder 10.000 kr!',
        views: 230000,
        uploadDate: 'For 3 uger siden',
        likes: 16100,
        duration: '17:35',
        thumbnailUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@BrizzeFC/videos',
      },
      {
        id: 'bz-5',
        title: 'Lærer en komplet nybegynder et verdenstrick på 1 time',
        views: 140000,
        uploadDate: 'For 1 måned siden',
        likes: 9800,
        duration: '19:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@BrizzeFC/videos',
      },
    ],
    bio: 'Professionel panna- og freestyle fodboldspiller. Vilde fodboldtricks, challenges med stjerner og crossbar trials.',
    joinedYear: 2015,
    topAudienceAge: '10-24 år',
  },
  {
    id: 'rebecca-dahl',
    name: 'Rebecca Charlotte Dahl',
    channelName: 'Rebecca Charlotte Dahl',
    handle: '@RebeccaDahl',
    avatarUrl:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Vlogs & Livsstil',
    subscribers: 178000,
    totalViews: 99400000,
    monthlyViews: 2400000,
    monthlyGrowthPct: 7.2,
    monthlySubGain: 1400,
    videoCount: 560,
    avgViewsPerVideo: 177500,
    engagementRate: 6.0,
    rankPosition: 11,
    bestPostingTime: {
      day: 'Søndag',
      hours: '10:00 - 12:30',
      score: 91,
      boostPercent: 23,
      recommendation:
        'Søndag morgen/formiddag passer optimalt til morgenkaffe-vlogs og ugentlige livsstilsopdateringer.',
    },
    weeklyHeatmap: generateHeatmap('Søndag', 2),
    recentVideos: [
      {
        id: 'rc-1',
        title: 'En ærlig ugevlog: Op- og nedture og nye projekter',
        views: 135000,
        uploadDate: 'For 2 dage siden',
        likes: 9800,
        duration: '24:10',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RebeccaDahl/videos',
      },
      {
        id: 'rc-2',
        title: 'Vi renoverer vores nye soveværelse (Makeover)',
        views: 165000,
        uploadDate: 'For 6 dage siden',
        likes: 12100,
        duration: '21:30',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RebeccaDahl/videos',
      },
      {
        id: 'rc-3',
        title: 'Hvad spiser jeg på en hel dag? (Nem & sund inspiration)',
        views: 110000,
        uploadDate: 'For 1 uge siden',
        likes: 8400,
        duration: '16:45',
        thumbnailUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RebeccaDahl/videos',
      },
      {
        id: 'rc-4',
        title: 'Min garderobe før & efter stor udrensning',
        views: 145000,
        uploadDate: 'For 2 uger siden',
        likes: 10600,
        duration: '19:20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RebeccaDahl/videos',
      },
      {
        id: 'rc-5',
        title: 'En hyggelig søndag i København med veninderne',
        views: 125000,
        uploadDate: 'For 3 uger siden',
        likes: 9100,
        duration: '22:00',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@RebeccaDahl/videos',
      },
    ],
    bio: 'Hyggelige hverdags-vlogs, indretning, mode og ærlige snakke om livet og relationer.',
    joinedYear: 2013,
    topAudienceAge: '14-30 år',
  },
  {
    id: 'lakserytteren',
    name: 'Rasmus Kolbe (Lakserytteren)',
    channelName: 'Lakserytteren',
    handle: '@Lakserytteren',
    avatarUrl:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=320&q=80',
    verified: true,
    category: 'Underholdning',
    subscribers: 138000,
    totalViews: 64200000,
    monthlyViews: 1850000,
    monthlyGrowthPct: 11.4,
    monthlySubGain: 1900,
    videoCount: 380,
    avgViewsPerVideo: 168900,
    engagementRate: 6.9,
    rankPosition: 12,
    bestPostingTime: {
      day: 'Onsdag',
      hours: '16:00 - 18:30',
      score: 89,
      boostPercent: 20,
      recommendation:
        'Midt på ugen efter skoletid, hvor tegne-glade unge søger kreativ inspiration.',
    },
    weeklyHeatmap: generateHeatmap('Onsdag', 4),
    recentVideos: [
      {
        id: 'lr-1',
        title: 'Jeg malede en hel bil med Posca-tuscher!',
        views: 182000,
        uploadDate: 'For 3 dage siden',
        likes: 14200,
        duration: '16:30',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@Lakserytteren/videos',
      },
      {
        id: 'lr-2',
        title: 'Tegner hvad 100 tilfældige børn beder mig om!',
        views: 210000,
        uploadDate: 'For 1 uge siden',
        likes: 16800,
        duration: '18:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@Lakserytteren/videos',
      },
      {
        id: 'lr-3',
        title: 'Forvandler en gammel guitar til et vildt kunstværk',
        views: 155000,
        uploadDate: 'For 2 uger siden',
        likes: 11900,
        duration: '14:50',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@Lakserytteren/videos',
      },
      {
        id: 'lr-4',
        title: 'Tegne-challenge mod en professionel kunstner',
        views: 170000,
        uploadDate: 'For 3 uger siden',
        likes: 13400,
        duration: '21:00',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@Lakserytteren/videos',
      },
      {
        id: 'lr-5',
        title: '24 timer hvor jeg kun må tegne med KETCHUP og SENNEP',
        views: 195000,
        uploadDate: 'For 1 måned siden',
        likes: 15600,
        duration: '17:25',
        thumbnailUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=400&q=80',
        url: 'https://www.youtube.com/@Lakserytteren/videos',
      },
    ],
    bio: 'Kreativt geni, tegninger, forvandlinger af mærkelige genstande og vilde kunstprojekter.',
    joinedYear: 2016,
    topAudienceAge: '8-18 år',
  },
];

// Initial default seed favorites so the app feels immediate and ready
export const DEFAULT_FAVORITE_IDS = ['alexander-husum', 'morten-munster', 'jas-mika'];
